#!/bin/bash
#SBATCH --partition=normal
#SBATCH --job-name=jbottenb_cs678
#SBATCH --output=/home/jbottenb/output/cs678/preprocessing.%j.out
#SBATCH --error=/home/jbottenb/output/cs678/preprocessing.%j.out
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4G
#SBATCH --export=ALL
#SBATCH --time=0-10:00:00

set echo 
umask 0022

## Load the necessary modules
module load gnu10 python cuda

## Execute your script
echo 'Running main script...'
bash /home/jbottenb/repositories/cs678/project/control_hopper.bash
